### PR TITLE
Bump expo-config-plugins dependency

### PR DESCRIPTION
**Pull request by maxenceg**
Related to https://github.com/cmaycumber/config-plugin-react-native-intercom/issues/62

### CODE REVIEW

**Comment by maxenceg** [comment]
Hi @cmaycumber!

I've opened this PR because `npx expo-doctor` says that `@expo/config-plugins` should match version `~6.0.0`

image

**Comment by gunnartorfis** [comment]
Can we get a release with this? @cmaycumber

**Comment by alistairholt** [comment]
A release, please! 🙏

**Comment by d3v4nt** [comment]
sorry my fault, I still have issues with the `config-plugins` dependency, any idea how to solve that?

expo doctor:
Screenshot 2023-06-13 at 10 16 53

npm why
Screenshot 2023-06-13 at 10 16 40

**Pull request merged**
