### PR TITLE
chore: update ios config plugin

### PR DESCRIPTION
**Pull request by elmaxe**
See: https://github.com/cmaycumber/config-plugin-react-native-intercom/issues/56

Fixes: #56

### CODE REVIEW

**Comment by enagorny** [comment]
This is likely needs to be a version bump, as this will make impossible to work with SDK47

**Comment by WadhahEssam** [comment]
the change is only one line, the rest is code styling? I think it would be better if you remove the styling @elmaxe

**Comment by elmaxe** [comment]
> the change is only one line, the rest is code styling? I think it would be better if you remove the styling @elmaxe

Yeah it seems so. Not my commit. I can fix

**Comment by elmaxe** [comment]
Fixed @WadhahEssam

**Comment by enagorny** [comment]
I've merged the fix code and update the readme.md. 
But I don't have right to update it on the npm. For now you can install it using gitpkg.now.sh `npm install 'https://gitpkg.now.sh/cmaycumber/config-plugin-react-native-intercom/packages/intercom-react-native?main'`

@cmaycumber could you please publish it on npm? and sorry for merging it early

**Comment by alistairholt** [comment]
Just a heads up that this still isn't working for us. We’re on SDK 48 and have the latest version installed from Yarn (1.10.1 - March 20 2023). I checked `node_modules` to double-check that is has the fix from this PR and it does.

```
[CoreFoundation] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull code]: unrecognized selector sent to
instance 0x1bbb347d8'
*** First throw call stack:
(
0   CoreFoundation                      0x0000000180437330 __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x0000000180051274 objc_exception_throw + 56
2   CoreFoundation                      0x0000000180445e3c +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
3   CoreFoundation                      0x000000018043b224 ___forwarding___ + 1308
4   CoreFoundation                      0x000000018043d50c _CF_forwarding_prep_0 + 92
5   TheApp                            0x0000000100f94668 RCTJSErrorFromCodeMessageAndNSError + 736
6   TheApp                            0x0000000100f94348 RCTJSErrorFromNSError + 236
7   TheApp                            0x0000000100f30e14 __41-[RCTModuleMethod processMethodSignature]_block_invoke_4.56 + 132
8   TheApp                            0x00<…>
```

**Pull request merged**
