### PR TITLE
Stop overwriting build properties

### LINKED ISSUE #51: Build properties set to incompatible values
Hi,

In #49, the readme was updated to tell people to set `compileSdkVersion` and `targetSdkVersion` to 33 or higher.

But this package/plugin already has that functionality built in! Except it's setting the value to 31.

https://github.com/cmaycumber/config-plugin-react-native-intercom/blob/993f0069e3e12b861706f879a49afe829b556fa6/packages/intercom-react-native/src/withIntercom.ts#L75-L77

In the app.json plugins array, it seems that precedence goes to the earlier items in the array.

So this works (builds with v33):

```json
{
	"plugins": [
		["expo-build-properties", { "android": { "compileSdkVersion": 33, "targetSdkVersion": 33 } }],
		["config-plugin-react-native-intercom", {}]
	]
}
```

But in the other order, it doesn't work (actually builds with v31):

```json
{
	"plugins": [
		["config-plugin-react-native-intercom", {}],
		["expo-build-properties", { "android": { "compileSdkVersion": 33, "targetSdkVersion": 33 } }]
	]
}
```

You could potentially fix this by updating the version in `withIntercom.ts` to 33, but to be honest I don't think it's really right for a plugin like this to be setting exact values for critical build settings which affect the entire project.

I'd suggest removing this package's use of expo-build-properties, and just leaving it as a documented requirement

### PR DESCRIPTION
**Pull request by billinghamj**
Instead of forcing apps to use specific build properties, just document the requirements

Fixes #51

### CODE REVIEW

**Comment by enagorny** [comment]
Having build properties defined outside this library might be better. As Intercom is usually meant to be used in larger apps which tend to have a lot other dependencies.

**Review by enagorny — APPROVED** [review]

**Comment by billinghamj** [comment]
@cmaycumber Would you be able to have a look over this? :)

**Comment by billinghamj** [comment]
@cmaycumber Sorry to nag, but this is quite a serious issue - would appreciate if it can be considered

**Comment by cmaycumber** [comment]
> @cmaycumber Sorry to nag, but this is quite a serious issue - would appreciate if it can be considered

No worries please nag. Sorry I’ve been quite busy. 

I’ll get this merged in later today.

**Comment by cmaycumber** [comment]
@enagorny I’m going to add you as a collaberator if you’d like and add some CI to auto deploy changes to NPM. Would you be alright with that?

**Comment by enagorny** [comment]
@cmaycumber  I would be happy to accept

**Comment by cmaycumber** [comment]
@billinghamj Published in v1.8

**Pull request merged**
