### PR TITLE
:arrow_up: bump expo-config-plugins and expo-build-properties dependencies

### PR DESCRIPTION
**Pull request by maximechbt**

### CODE REVIEW

**Comment by maximechbt** [comment]
> Thanks! Will deploy these changes tonight!

@cmaycumber Can you deploy please? 🙏

**Comment by cmaycumber** [comment]
Sorry this is taking so long! Deploying today.

**Comment by cmaycumber** [comment]
@maximechbt Should be here: https://www.npmjs.com/package/config-plugin-react-native-intercom/v/1.6.10

**Comment by cmaycumber** [comment]
Curious if you're interested in helping maintain as well. 

I don't actually use Intercom anymore so any help would be greatly appreciated.

**Pull request merged**
