### PR TITLE
Support Expo 50

### PR DESCRIPTION
**Pull request by Billzabob**
Applies the changes [from the patch here](https://github.com/cmaycumber/config-plugin-react-native-intercom/issues/77#issuecomment-1902533395)

### CODE REVIEW

**Comment by hanyufoodles** [comment]
Thank you so much!

**Comment by ansh** [comment]
Please merge @cmaycumber

**Comment by saurabhg138** [comment]
Any timeline to merge this? @cmaycumber

**Comment by reichhartd** [comment]
Since the last [version 6.5.0](https://github.com/intercom/intercom-react-native/releases/tag/6.5.0) `intercom/intercom-react-native` offers a first class expo plugin, so this PR and package should no longer be necessary.

**Comment by saurabhg138** [comment]
@reichhartd I am getting error Failed to resolve plugin for module "@config-plugins/intercom-react-native" . Can you help me resolve it?

**Comment by reichhartd** [comment]
This was only intended as information. I am not a maintainer of the package. However, [the error seems to be known and is being worked on](https://github.com/intercom/intercom-react-native/pull/155#issuecomment-1963710389).

**Comment by CarlMenke** [comment]
I may be lost, but any idea why this was closed an not merged?

**Pull request closed without merging**
